name: Java CI

on: [push, pull_request]  # Runs on every code push or pull request

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Fetches your code

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install  # Runs build and tests

      - name: Run tests
        run: mvn test  # Executes JUnit tests
